FROM debian:bullseye

LABEL maintainer="developer@s.vrx.pl"
LABEL version="2.0"
LABEL description="Bacula Server 9.6"

ARG DEBIAN_FRONTEND=noninteractive
ARG DB

RUN echo "path-exclude /usr/share/doc/*" > /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-include /usr/share/doc/*/copyright" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/man/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/groff/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/info/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/lintian/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/linda/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc&& \
    apt update && apt install -y gnupg2 && \
    apt update && apt install -y curl sudo && \
    echo "deb http://www.bacula.org/downloads/baculum/stable/debian buster main" > /etc/apt/sources.list.d/baculum.list && \
    echo "deb-src http://www.bacula.org/downloads/baculum/stable/debian buster main" >> /etc/apt/sources.list.d/baculum.list && \
    curl -sL http://www.bacula.org/downloads/baculum/baculum.pub | apt-key add - && \
    apt update && apt -y upgrade && apt install -y --no-install-recommends supervisor bacula-bscan bacula-common bacula-common-${DB} bacula-console bacula-director bacula-director-${DB} bacula-fd bacula-sd bacula-server apache2 baculum-api baculum-api-apache2 baculum-common baculum-web baculum-web-apache2 && \
    apt --purge remove -y curl gnupg2 && \
    apt autoremove -y && \
    rm -rf /var/cache/apt/* && \
    apt clean && \
    mkdir -p /var/www/bacula && \
    chown www-data:www-data /var/www/bacula && \
    mv /etc/bacula /opt/ && \
    mv /etc/baculum /opt/ && \
    mkdir -p /mnt/bacula && \
    mkdir -p /opt/lib && \
    mv /var/lib/bacula /opt/lib/ && \
    chown bacula:tape /opt/lib/bacula && \
    a2ensite baculum-api && \
    a2ensite baculum-web && \
    a2enmod rewrite && \
    usermod -aG tape www-data && \
    usermod -aG bacula www-data

COPY conf/9.6/sudoers /etc/sudoers
COPY conf/9.6/bacula-fd.conf /opt/bacula/bacula-fd.conf
COPY conf/9.6/bacula-sd.conf /opt/bacula/bacula-sd.conf
COPY conf/9.6/${DB}/bacula-dir.conf /opt/bacula/bacula-dir.conf
COPY conf/bconsole.conf /opt/bacula/bconsole.conf
COPY conf/9.6/${DB}/api.conf /opt/baculum/Config-api-apache/api.conf
COPY conf/baculum.users /opt/baculum/Config-api-apache/baculum.users
COPY conf/baculum.users /opt/baculum/Config-web-apache/baculum.users
COPY conf/hosts.conf /opt/baculum/Config-web-apache/hosts.conf
COPY conf/9.6/users.conf /opt/baculum/Config-web-apache/users.conf
COPY conf/settings.conf /opt/baculum/Config-web-apache/settings.conf
COPY db/9.6/${DB}/bacula.sql /opt/bacula.db
COPY conf/supervisord.conf /etc/supervisord.conf
COPY scripts/9.6/${DB}/entrypoint.sh /usr/sbin/entrypoint.sh

RUN chgrp bacula /opt/bacula/bacula-fd.conf && \
    chgrp bacula /opt/bacula/bacula-sd.conf && \
    chgrp bacula /opt/bacula/bacula-dir.conf 
    
VOLUME ["/etc/bacula", "/etc/baculum", "/var/lib/bacula", "/var/log/bacula", "/var/log/apache2"]

EXPOSE 9101/tcp 9103/tcp 9095/tcp 9096/tcp

ENTRYPOINT ["entrypoint.sh"]
