FROM debian:bullseye

LABEL maintainer="developer@s.vrx.pl"
LABEL version="2.1"
LABEL description="Bacula Server 11"

ARG DEBIAN_FRONTEND=noninteractive
ARG DB

RUN echo "path-exclude /usr/share/doc/*" > /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-include /usr/share/doc/*/copyright" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/man/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/groff/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/info/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/lintian/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo "path-exclude /usr/share/linda/*" >> /etc/dpkg/dpkg.cfg.d/01_nodoc&& \
    apt update && apt install -y gnupg2 curl sudo && \
    echo "deb http://www.bacula.org/downloads/baculum/stable-11/debian bullseye main" > /etc/apt/sources.list.d/baculum.list && \
    echo "deb-src http://www.bacula.org/downloads/baculum/stable-11/debian bullseye main" >> /etc/apt/sources.list.d/baculum.list && \
    echo "deb http://www.bacula.org/packages/614321e9d6b75/debs/11.0.5/bullseye/amd64 bullseye main" > /etc/apt/sources.list.d/bacula.list && \
    curl -sL http://www.bacula.org/downloads/baculum/baculum.pub | apt-key add - && \
    curl -sL https://www.bacula.org/downloads/Bacula-4096-Distribution-Verification-key.asc | apt-key add - && \
    apt update && apt -y upgrade && apt install -y --no-install-recommends lsscsi fuse procinfo mtx mt-st pv mbuffer supervisor bacula-client bacula-common bacula-console bacula-${DB} apache2 baculum-api baculum-api-apache2 baculum-common baculum-web baculum-web-apache2 && \
    apt --purge remove -y curl gnupg2 && \
    apt autoremove -y && \
    rm -rf /var/cache/apt/* && \
    apt clean && \
    echo "st" >> /etc/modules && \
    mkdir -p /var/www/bacula && \
    chown www-data:www-data /var/www/bacula && \
    mkdir /home/bacula && \
    mv /opt/bacula/scripts /home/bacula/ && \
    mv /opt/bacula/etc /home/bacula/ && \
    mv /opt/bacula/working /home/bacula/ && \
    mv /etc/baculum /home/ && \
    mkdir -p /mnt/bacula && \
    mkdir -p /home/lib && \
    mv /var/lib/bacula /home/lib/ && \
    chown bacula:tape /home/lib/bacula && \
    a2ensite baculum-api && \
    a2ensite baculum-web && \
    a2enmod rewrite && \
    usermod -aG tape www-data && \
    usermod -aG bacula www-data

COPY conf/11/sudoers /etc/sudoers
COPY conf/11/bacula-fd.conf /home/bacula/etc/bacula-fd.conf
COPY conf/11/bacula-sd.conf /home/bacula/etc/bacula-sd.conf
COPY conf/11/${DB}/bacula-dir.conf /home/bacula/etc/bacula-dir.conf
COPY conf/bconsole.conf /home/bacula/etc/bconsole.conf
COPY conf/11/${DB}/api.conf /home/baculum/Config-api-apache/api.conf
COPY conf/baculum.users /home/baculum/Config-api-apache/baculum.users
COPY conf/baculum.users /home/baculum/Config-web-apache/baculum.users
COPY conf/hosts.conf /home/baculum/Config-web-apache/hosts.conf
COPY conf/11/users.conf /home/baculum/Config-web-apache/users.conf
COPY conf/settings.conf /home/baculum/Config-web-apache/settings.conf
COPY db/11/${DB}/bacula.sql /home/bacula.db
COPY conf/supervisord.conf /etc/supervisord.conf
COPY scripts/11/${DB}/entrypoint.sh /usr/sbin/entrypoint.sh

RUN chgrp bacula /home/bacula/etc/bacula-fd.conf && \
    chgrp bacula /home/bacula/etc/bacula-sd.conf && \
    chgrp bacula /home/bacula/etc/bacula-dir.conf 
    
VOLUME ["/opt/bacula/etc", "/opt/bacula/working", "/opt/bacula/log", "/etc/baculum", "/var/log/apache2"]

EXPOSE 9101/tcp 9103/tcp 9095/tcp 9096/tcp

ENTRYPOINT ["entrypoint.sh"]
CMD ["supervisord","-n","-c","/etc/supervisord.conf"]
