#!/bin/bash

now=$(date +%d%H%M)
if [ "$now" == "010001" ] || [ "$now" == "010002" ]; then 
	cp -p /var/log/apache2/access.log{,.old} && :> /var/log/apache2/access.log
	cp -p /var/log/apache2/error.log{,.old} && :> /var/log/apache2/error.log
fi

health=0

#checking director
dir_pid=$(cat /opt/bacula/working/*dir*pid)
dir_check=$(ps aux | grep $dir_pid | grep -v grep | wc -l)
if [ "$dir_pid" != "" ] && [ "$dir_check" ]; then
	health=$((health+1))
fi

#checking sd
sd_pid=$(cat /opt/bacula/working/*sd*pid)
sd_check=$(ps aux | grep $sd_pid | grep -v grep | wc -l)
if [ "$sd_pid" != "" ] && [ $sd_check != 0 ]; then
	health=$((health+2))
fi

#checking fd
fd_pid=$(cat /opt/bacula/working/*fd*pid)
fd_check=$(ps aux | grep $fd_pid | grep -v grep | wc -l)
if [ "$fd_pid" != "" ] && [ $fd_check != 0 ]; then
	health=$((health+4))
fi

#checking web
web_pid=$(cat /run/apache2/apache2.pid)
web_check=$(ps aux | grep $web_pid | grep -v grep | wc -l)
if [ "$web_pid" != "" ] && [ "$web_check" ]; then
	health=$((health+8))
fi

#checking supervisor
sup_pid=$(cat /run/supervisord.pid)
sup_check=$(ps aux | grep $sup_pid | grep -v grep | wc -l)
if [ "$sup_pid" != "" ] && [ "$sup_check" ]; then
	health=$((health+16))
fi

#checking bacularis
bac=$(curl -s -I localhost:9097 | grep HTTP | cut -d " " -f 2)
if [ "$bac" = "401" ] || [ "$bac" = "301" ] || [ "$bac" = "302" ] || [ "$bac" = "200" ]; then
	health=$((health+32))
fi

if [ "$health" == 63 ]; then
	exit 0
else
	exit 1
fi
